#!/bin/sh
#
# Sync token colorscheme contrib files into dotfiles.
# Run after 'make contrib' in the token repo.
#
# Usage: ./sync_token_themes.sh [TOKEN_REPO_PATH]
#   TOKEN_REPO_PATH defaults to ../token (sibling directory)

set -eu

DOTFILES_DIR="$(cd "$(dirname "$0")" && pwd)"
TOKEN_DIR="${1:-$(cd "$DOTFILES_DIR/.." && pwd)/token}"
CONTRIB="$TOKEN_DIR/contrib"

errors=0

err() {
  printf "ERROR: %s\n" "$1" >&2
  errors=$((errors + 1))
}

info() {
  printf "  %s\n" "$1"
}

require_file() {
  if [ ! -f "$1" ]; then
    err "missing source: $1"
    return 1
  fi
}

require_dir() {
  if [ ! -d "$1" ]; then
    err "missing directory: $1"
    return 1
  fi
}

copy_file() {
  src="$1"
  dst="$2"
  require_file "$src" || return 1
  mkdir -p "$(dirname "$dst")"
  cp "$src" "$dst"
  info "$dst"
}

palette_value() {
  palette_file="$1"
  palette_key="$2"

  awk -v key="$palette_key" '
    $1 == key && $2 == "=" {
      gsub(/"/, "", $3)
      print $3
      found = 1
      exit
    }
    END { if (!found) exit 1 }
  ' "$palette_file"
}

# ------------------------------------------------------------------
# Preflight
# ------------------------------------------------------------------

if [ ! -d "$TOKEN_DIR" ]; then
  printf "ERROR: token repo not found at %s\n" "$TOKEN_DIR" >&2
  printf "Usage: %s [TOKEN_REPO_PATH]\n" "$0" >&2
  exit 1
fi

require_dir "$CONTRIB" || exit 1

appearances='token token-flint token-temper token-ultra'
modes='dark light'

for appearance in $appearances; do
  if ! require_file "$CONTRIB/delta/$appearance.gitconfig"; then
    :
  fi

  for mode in $modes; do
    for source in \
      "bat/$appearance-$mode.tmTheme" \
      "carapace/$appearance-$mode.json" \
      "fzf/$appearance-$mode.zsh" \
      "ghostty/$appearance-$mode" \
      "lazygit/$appearance-$mode.yml" \
      "ripgrep/$appearance-$mode.ripgreprc" \
      "starship/$appearance-$mode.toml" \
      "tmux/$appearance-$mode.conf" \
      "zsh/$appearance-$mode.zsh"; do
      if ! require_file "$CONTRIB/$source"; then
        :
      fi
    done
  done
done

if ! require_file "$DOTFILES_DIR/ripgrep/.config/ripgrep/config"; then
  :
fi

if [ "$errors" -gt 0 ]; then
  printf "Finished with %d error(s).\n" "$errors" >&2
  exit 1
fi

printf "Syncing token themes from %s\n" "$CONTRIB"
printf "Into dotfiles at %s\n\n" "$DOTFILES_DIR"

# ------------------------------------------------------------------
# Bat
# ------------------------------------------------------------------

printf "bat:\n"
for appearance in $appearances; do
  for mode in $modes; do
    copy_file "$CONTRIB/bat/$appearance-$mode.tmTheme" \
      "$DOTFILES_DIR/bat/.config/bat/themes/$appearance-$mode.tmTheme"
  done
done

# ------------------------------------------------------------------
# Carapace (completion styling)
# ------------------------------------------------------------------

printf "carapace:\n"
for appearance in $appearances; do
  for mode in $modes; do
    copy_file "$CONTRIB/carapace/$appearance-$mode.json" \
      "$DOTFILES_DIR/zsh/.config/zsh/themes/carapace-$appearance-$mode.json"
  done
done

# ------------------------------------------------------------------
# Delta (git)
# ------------------------------------------------------------------

printf "delta:\n"
delta_dst="$DOTFILES_DIR/git/.config/git/delta_themes.inc"
{
  printf '%s\n\n' '# Generated by token colorscheme. Do not edit manually.'
  first_delta=1
  for appearance in $appearances; do
    if [ "$first_delta" -eq 0 ]; then
      printf '\n'
    fi
    sed -n '/^\[delta /,$p' "$CONTRIB/delta/$appearance.gitconfig"
    first_delta=0
  done
} >"$delta_dst"
info "$delta_dst"

# ------------------------------------------------------------------
# Git (adapted from the Token Starship palette)
# ------------------------------------------------------------------

printf "git:\n"
for appearance in $appearances; do
  for mode in $modes; do
    src="$CONTRIB/starship/$appearance-$mode.toml"
    dst="$DOTFILES_DIR/git/.config/git/$appearance-$mode.gitconfig"

    if ! fg=$(palette_value "$src" fg) ||
      ! muted=$(palette_value "$src" muted) ||
      ! subtle=$(palette_value "$src" subtle) ||
      ! accent=$(palette_value "$src" accent) ||
      ! blue=$(palette_value "$src" blue) ||
      ! green=$(palette_value "$src" green) ||
      ! red=$(palette_value "$src" red) ||
      ! yellow=$(palette_value "$src" yellow) ||
      ! purple=$(palette_value "$src" purple) ||
      ! cyan=$(palette_value "$src" cyan) ||
      ! orange=$(palette_value "$src" orange); then
      err "incomplete palette in $src"
      continue
    fi

    mkdir -p "$(dirname "$dst")"
    cat >"$dst" <<EOF
# Generated from the $appearance $mode palette. Do not edit manually.

[color "advice"]
	hint = "$cyan"

[color "blame"]
	repeatedLines = "$subtle"

[color "branch"]
	current = "bold $accent"
	local = "bold $blue"
	plain = "$fg"
	remote = "bold $cyan"
	upstream = "bold $cyan"
	worktree = "bold $purple"

[color "decorate"]
	HEAD = "bold $accent"
	branch = "bold $green"
	grafted = "$muted"
	remoteBranch = "bold $cyan"
	stash = "$purple"
	tag = "bold $orange"

[color "diff"]
	# Keep glg's commit colour, but let delta style diff bodies.
	commit = "$blue"

[color "grep"]
	column = "$cyan"
	context = "$muted"
	filename = "bold $blue"
	function = "$purple"
	lineNumber = "$yellow"
	match = "bold $accent"
	matchContext = "bold $accent"
	matchSelected = "bold $accent"
	selected = "$fg"
	separator = "$subtle"

[color "interactive"]
	error = "bold $red"
	header = "bold $purple"
	help = "$muted"
	plain = "$fg"
	prompt = "bold $accent"

[color "push"]
	error = "bold $red"

[color "remote"]
	error = "bold $red"
	hint = "$cyan"
	success = "$green"
	warning = "$yellow"

[color "status"]
	added = "$green"
	branch = "bold $accent"
	changed = "bold $yellow"
	header = "$muted"
	localBranch = "$blue"
	noBranch = "bold $red"
	remoteBranch = "$cyan"
	unmerged = "bold $red"
	untracked = "$cyan"
	updated = "$green"

[color "transport"]
	rejected = "bold $red"
EOF
    info "$dst"
  done
done

# ------------------------------------------------------------------
# FZF (zsh variants)
# ------------------------------------------------------------------

printf "fzf (zsh):\n"
for appearance in $appearances; do
  for mode in $modes; do
    copy_file "$CONTRIB/fzf/$appearance-$mode.zsh" \
      "$DOTFILES_DIR/fzf/.config/fzf/themes/$appearance-$mode.zsh"
  done
done

# ------------------------------------------------------------------
# Zsh (syntax highlighting + completion theme)
# ------------------------------------------------------------------

printf "zsh:\n"
for appearance in $appearances; do
  for mode in $modes; do
    copy_file "$CONTRIB/zsh/$appearance-$mode.zsh" \
      "$DOTFILES_DIR/zsh/.config/zsh/themes/$appearance-$mode.zsh"
  done
done

# ------------------------------------------------------------------
# Ghostty
# ------------------------------------------------------------------

printf "ghostty:\n"
for appearance in $appearances; do
  for mode in $modes; do
    copy_file "$CONTRIB/ghostty/$appearance-$mode" \
      "$DOTFILES_DIR/ghostty/.config/ghostty/themes/$appearance-$mode"
  done
done

# ------------------------------------------------------------------
# Lazygit
# ------------------------------------------------------------------

printf "lazygit:\n"
for appearance in $appearances; do
  for mode in $modes; do
    copy_file "$CONTRIB/lazygit/$appearance-$mode.yml" \
      "$DOTFILES_DIR/lazygit/.config/lazygit/$appearance-$mode.yml"
  done
done

# ------------------------------------------------------------------
# Ripgrep (adapted: prepend base config, append token colors)
# ------------------------------------------------------------------

printf "ripgrep:\n"
rg_base="$DOTFILES_DIR/ripgrep/.config/ripgrep/config"
rg_base_lines=$(grep -v '^--color' "$rg_base")

for appearance in $appearances; do
  for mode in $modes; do
    src="$CONTRIB/ripgrep/$appearance-$mode.ripgreprc"
    dst="$DOTFILES_DIR/ripgrep/.config/ripgrep/themes/$appearance-$mode"

    # Token contrib color lines (skip comment header)
    rg_colors=$(grep '^--' "$src")

    mkdir -p "$(dirname "$dst")"
    printf "%s\n%s\n" "$rg_base_lines" "$rg_colors" >"$dst"
    info "$dst"
  done
done

# ------------------------------------------------------------------
# Starship (adapted: prepend the selected palette directive)
# ------------------------------------------------------------------

printf "starship:\n"
for appearance in $appearances; do
  for mode in $modes; do
    src="$CONTRIB/starship/$appearance-$mode.toml"
    dst="$DOTFILES_DIR/starship/.config/src/palettes/$appearance-$mode.toml"
    if ! require_file "$src"; then
      continue
    fi

    # Token contrib has a palette section but no top-level palette directive.
    palette_section=$(sed -n '/^\[palettes\./,$p' "$src")
    if [ -z "$palette_section" ]; then
      err "no [palettes.*] section found in $src"
      continue
    fi

    mkdir -p "$(dirname "$dst")"
    printf 'palette = "%s"\n\n%s\n' "$appearance" "$palette_section" >"$dst"
    info "$dst"
  done
done

# Regenerate starship configs from source
sh "$DOTFILES_DIR/starship/.config/src/generate.sh"
info "starship configs regenerated"

# ------------------------------------------------------------------
# Tmux
# ------------------------------------------------------------------

printf "tmux:\n"
for appearance in $appearances; do
  for mode in $modes; do
    copy_file "$CONTRIB/tmux/$appearance-$mode.conf" \
      "$DOTFILES_DIR/tmux/.config/tmux/$appearance-$mode.conf"
  done
done

# ------------------------------------------------------------------
# Summary
# ------------------------------------------------------------------

printf "\n"
if [ "$errors" -gt 0 ]; then
  printf "Finished with %d error(s).\n" "$errors" >&2
  exit 1
fi
printf "All token themes synced successfully.\n"
