notARepository: "quit"
promptToReturnFromSubprocess: false
gui:
  showIcons: true
  nerdFontsVersion: "3"
  timeFormat: "2006-01-02 15:04:05 MST"
git:
  diffRenderers:
    - colorArg: always
      command: delta --paging=never
update:
  method: prompt
  days: 14
