[delta "melange-light"]
	blame-palette = "#F1F1F1 #E9E1DB #D9D3CE #A98A78 #7D6658"
	commit-decoration-style = "#A98A78" bold box ul
	light = true
	file-decoration-style = "#A98A78"
	file-style = "#54433A"
	hunk-header-decoration-style = "#A98A78" box ul
	hunk-header-file-style = bold
	hunk-header-line-number-style = bold "#7D6658"
	hunk-header-style = file line-number syntax
	line-numbers-left-style = "#A98A78"
	line-numbers-minus-style = bold "#BF0021"
	line-numbers-plus-style = bold "#3A684A"
	line-numbers-right-style = "#A98A78"
	line-numbers-zero-style = "#A98A78"
	# 35% red 65% base
	minus-emph-style = bold syntax "#e5bcc4"
	# 20% red 80% base
	minus-style = syntax "#eed5da"
	# 35% green 65% base
	plus-emph-style = bold syntax "#c4ddc8"
	# 20% green 80% base
	plus-style = syntax "#ddeadf"
	map-styles = \
		bold purple => syntax "#d9c7e0", \
		bold blue => syntax "#c9d2e3", \
		bold cyan => syntax "#cfe2e2", \
		bold yellow => syntax "#e7d7c1"
	# Should match the name of the bat theme
	syntax-theme = Melange Light

[delta "catppuccin-frappe"]
	blame-palette = "#303446 #292c3c #232634 #414559 #51576d"
	commit-decoration-style = "#737994" bold box ul
	dark = true
	file-decoration-style = "#737994"
	file-style = "#c6d0f5"
	hunk-header-decoration-style = "#737994" box ul
	hunk-header-file-style = bold
	hunk-header-line-number-style = bold "#a5adce"
	hunk-header-style = file line-number syntax
	line-numbers-left-style = "#737994"
	line-numbers-minus-style = bold "#e78284"
	line-numbers-plus-style = bold "#a6d189"
	line-numbers-right-style = "#737994"
	line-numbers-zero-style = "#737994"
	# 35% red 65% base
	minus-emph-style = bold syntax "#704f5c"
	# 20% red 80% base
	minus-style = syntax "#544452"
	# 35% green 65% base
	plus-emph-style = bold syntax "#596b5e"
	# 20% green 80% base
	plus-style = syntax "#475453"
	map-styles = \
		bold purple => syntax "#66597e", \
		bold blue => syntax "#505d81", \
		bold cyan => syntax "#546b7a", \
		bold yellow => syntax "#6f6860"
	# Should match the name of the bat theme
	syntax-theme = Catppuccin Frappe

[delta "catppuccin-macchiato"]
	blame-palette = "#24273a #1e2030 #181926 #363a4f #494d64"
	commit-decoration-style = "#6e738d" bold box ul
	dark = true
	file-decoration-style = "#6e738d"
	file-style = "#cad3f5"
	hunk-header-decoration-style = "#6e738d" box ul
	hunk-header-file-style = bold
	hunk-header-line-number-style = bold "#a5adcb"
	hunk-header-style = file line-number syntax
	line-numbers-left-style = "#6e738d"
	line-numbers-minus-style = bold "#ed8796"
	line-numbers-plus-style = bold "#a6da95"
	line-numbers-right-style = "#6e738d"
	line-numbers-zero-style = "#6e738d"
	# 35% red 65% base
	minus-emph-style = bold syntax "#6a485a"
	# 20% red 80% base
	minus-style = syntax "#4c3a4c"
	# 35% green 65% base
	plus-emph-style = bold syntax "#51655a"
	# 20% green 80% base
	plus-style = syntax "#3e4b4c"
	map-styles = \
		bold purple => syntax "#5c517c", \
		bold blue => syntax "#47557b", \
		bold cyan => syntax "#4a6475", \
		bold yellow => syntax "#6a635d"
	# Should match the name of the bat theme
	syntax-theme = Catppuccin Macchiato

[delta "melange-dark"]
	blame-palette = "#292522 #34302C #403A36 #867462 #C1A78E"
	commit-decoration-style = "#867462" bold box ul
	dark = true
	file-decoration-style = "#867462"
	file-style = "#ECE1D7"
	hunk-header-decoration-style = "#867462" box ul
	hunk-header-file-style = bold
	hunk-header-line-number-style = bold "#C1A78E"
	hunk-header-style = file line-number syntax
	line-numbers-left-style = "#867462"
	line-numbers-minus-style = bold "#D47766"
	line-numbers-plus-style = bold "#85B695"
	line-numbers-right-style = "#867462"
	line-numbers-zero-style = "#867462"
	# 35% red 65% base
	minus-emph-style = bold syntax "#5e433f"
	# 20% red 80% base
	minus-style = syntax "#3f3634"
	# 35% green 65% base
	plus-emph-style = bold syntax "#4d5852"
	# 20% green 80% base
	plus-style = syntax "#3c443f"
	map-styles = \
		bold purple => syntax "#5b4d62", \
		bold blue => syntax "#4d5167", \
		bold cyan => syntax "#4c5460", \
		bold yellow => syntax "#655d52"
	# Should match the name of the bat theme
	syntax-theme = Melange Dark
