"$schema" = "https://starship.rs/config-schema.json"

add_newline     = true
command_timeout = 500
right_format    = "$cmd_duration"

[character]
error_symbol   = "[❯❯](bold red)"
success_symbol = "[❯❯](bold green)"

[hostname]
format     = "[$hostname  ](bold yellow)"
ssh_only   = true
ssh_symbol = " "

[username]
detect_env_vars = ["SSH_CLIENT", "SSH_CONNECTION", "SSH_TTY", "SUDO_USER"]
format          = "[$user]($style) "
show_always     = false
style_root      = "red bold"
style_user      = "green bold"

[git_branch]
symbol = " "

[cmd_duration]
format = "took [$duration]($style)"

[git_commit]
tag_disabled = false
tag_symbol   = '  '

[git_status]
ahead             = "[ ](green)"
behind            = "[ ](red)"
conflicted        = "[ ](red bold)"
deleted           = "[ ](red)"
disabled          = false
diverged          = "[ ](yellow)"
format            = "($all_status$ahead_behind )"
ignore_submodules = true
modified          = "[ ](yellow)"
renamed           = "[ ](purple)"
staged            = "[ ](green)"
stashed           = "[ ](dimmed)"
style             = "red"
untracked         = "[ ](blue)"

[git_metrics]
added_style   = "green"
deleted_style = "red"
disabled      = false
format        = "([ $added]($added_style) )([ $deleted]($deleted_style) )"

[aws]
symbol = " "

[buf]
symbol = " "

[bun]
symbol = " "

[c]
symbol = " "

[cpp]
symbol = " "

[cmake]
symbol = " "

[conda]
symbol = " "

[crystal]
symbol = " "

[dart]
symbol = " "

[deno]
symbol = " "

[directory]
read_only = " 󰌾"

[docker_context]
symbol = " "

[elixir]
symbol = " "

[elm]
symbol = " "

[fennel]
symbol = " "

[fossil_branch]
symbol = " "

[gcloud]
symbol = " "

[golang]
symbol = " "

[gradle]
symbol = " "

[guix_shell]
symbol = " "

[haskell]
symbol = " "

[haxe]
symbol = " "

[hg_branch]
symbol = " "

[java]
symbol = " "

[julia]
symbol = " "

[kotlin]
symbol = " "

[lua]
symbol = " "

[memory_usage]
symbol = "󰍛 "

[meson]
symbol = "󰔷 "

[nim]
symbol = "󰆥 "

[nix_shell]
symbol = " "

[nodejs]
symbol = " "

[ocaml]
symbol = " "

[os]
disabled = true

[package]
symbol = "󰏗 "

[perl]
symbol = " "

[php]
symbol = " "

[pijul_channel]
symbol = " "

[pixi]
symbol = "󰏗 "

[python]
detect_extensions = []
detect_folders    = []
format            = "[$symbol$virtualenv ($version)]($style) "
symbol            = " "

[rlang]
symbol = "󰟔 "

[ruby]
symbol = " "

[rust]
symbol = "󱘗 "

[scala]
symbol = " "

[status]
disabled = false
symbol   = " "

[swift]
symbol = " "

[zig]
symbol = " "
