
palette = "claude-light"

[palettes.claude-light]
bg0 = '#faf9f5'
bg1 = '#edece8'
fg = '#2a2920'
red = '#B05555'
orange = '#BB5C3A'
yellow = '#8A7735'
green = '#527E50'
aqua = '#996E3C'
blue = '#527594'
purple = '#82669D'
