
palette = "claude-light"

[palettes.claude-light]
bg0 = '#faf9f5'
bg1 = '#edece8'
fg = '#2a2920'
red = '#B05555'
orange = '#9A4929'
yellow = '#6E5C20'
green = '#3F643C'
aqua = '#876032'
blue = '#527594'
purple = '#7C619A'
